import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rendy
 */
public class AplikasiKonversiSuhuFrame extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhuFrame
     */
    public AplikasiKonversiSuhuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgKonversi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TSuhu = new javax.swing.JTextField();
        CbSkalaSuhu = new javax.swing.JComboBox<>();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        Rb3 = new javax.swing.JRadioButton();
        BKonversi = new javax.swing.JButton();
        LHasil = new javax.swing.JLabel();
        Rb4 = new javax.swing.JRadioButton();
        THasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 50, 255));

        LJudul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(255, 255, 255));
        LJudul.setText("Aplikasi Konversi Suhu");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan Suhu :");

        TSuhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TSuhuKeyTyped(evt);
            }
        });

        CbSkalaSuhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CbSkalaSuhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));

        BgKonversi.add(Rb1);
        Rb1.setText("Fahrenheit");

        BgKonversi.add(Rb2);
        Rb2.setText("Reamur");

        BgKonversi.add(Rb3);
        Rb3.setText("Kelvin");

        BKonversi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BKonversi.setText("Konversi Suhu");
        BKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKonversiActionPerformed(evt);
            }
        });

        LHasil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LHasil.setForeground(new java.awt.Color(255, 255, 255));
        LHasil.setText("Hasil Nilai Yang Di Konversi :");

        BgKonversi.add(Rb4);
        Rb4.setText("Celcius");

        THasil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(LJudul))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(BKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LHasil)
                                .addGap(18, 18, 18)
                                .addComponent(THasil))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Rb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7)
                                .addComponent(Rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(Rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CbSkalaSuhu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbSkalaSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb1)
                    .addComponent(Rb2)
                    .addComponent(Rb3)
                    .addComponent(Rb4))
                .addGap(18, 18, 18)
                .addComponent(BKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LHasil)
                    .addComponent(THasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKonversiActionPerformed
        try {
            // Mengambil nilai suhu dari input
            double suhuInput = Double.parseDouble(TSuhu.getText());
            double hasilKonversi = 0.0;

            // Menentukan konversi berdasarkan skala asal dan tujuan
            String skalaAsal = CbSkalaSuhu.getSelectedItem().toString();

            // Cek pilihan skala tujuan di JRadioButton
            if (skalaAsal.equals("Celcius")) {
                if (Rb1.isSelected()) {
                    hasilKonversi = suhuInput * 9/5 + 32;  // Celcius ke Fahrenheit
                } else if (Rb2.isSelected()) {
                    hasilKonversi = suhuInput * 4/5;       // Celcius ke Reamur
                } else if (Rb3.isSelected()) {
                    hasilKonversi = suhuInput + 273.15;    // Celcius ke Kelvin
                }
            } else if (skalaAsal.equals("Fahrenheit")) {
                if (Rb4.isSelected()) {
                    hasilKonversi = (suhuInput - 32) * 5/9;  // Fahrenheit ke Celcius
                } else if (Rb2.isSelected()) {
                    hasilKonversi = (suhuInput - 32) * 4/9;  // Fahrenheit ke Reamur
                } else if (Rb3.isSelected()) {
                    hasilKonversi = (suhuInput - 32) * 5/9 + 273.15;  // Fahrenheit ke Kelvin
                }
            } else if (skalaAsal.equals("Reamur")) {
                if (Rb4.isSelected()) {
                    hasilKonversi = suhuInput * 5/4;  // Reamur ke Celcius
                } else if (Rb1.isSelected()) {
                    hasilKonversi = suhuInput * 9/4 + 32;  // Reamur ke Fahrenheit
                } else if (Rb3.isSelected()) {
                    hasilKonversi = suhuInput * 5/4 + 273.15;  // Reamur ke Kelvin
                }
            } else if (skalaAsal.equals("Kelvin")) {
                if (Rb4.isSelected()) {
                    hasilKonversi = suhuInput - 273.15;  // Kelvin ke Celcius
                } else if (Rb1.isSelected()) {
                    hasilKonversi = (suhuInput - 273.15) * 9/5 + 32;  // Kelvin ke Fahrenheit
                } else if (Rb2.isSelected()) {
                    hasilKonversi = (suhuInput - 273.15) * 4/5;  // Kelvin ke Reamur
                }
            }

            // Menampilkan hasil konversi
            THasil.setText("" + hasilKonversi);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
        }
    }//GEN-LAST:event_BKonversiActionPerformed

    private void TSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TSuhuKeyTyped
        // Pembatasan input hanya angka, titik, dan backspace
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != '.') {
            evt.consume();  // Membatasi input hanya angka dan titik
        } else {
            // Lakukan konversi otomatis jika input valid
            try {
                double suhuInput = Double.parseDouble(TSuhu.getText() + c);
                double hasilKonversi = 0.0;

                String skalaAsal = CbSkalaSuhu.getSelectedItem().toString();

                if (skalaAsal.equals("Celcius")) {
                    if (Rb1.isSelected()) {
                        hasilKonversi = suhuInput * 9/5 + 32;
                    } else if (Rb2.isSelected()) {
                        hasilKonversi = suhuInput * 4/5;
                    } else if (Rb3.isSelected()) {
                        hasilKonversi = suhuInput + 273.15;
                    }
                }
                // Tambahkan konversi lain sesuai kebutuhan

                THasil.setText("" + hasilKonversi);

            } catch (NumberFormatException e) {
                THasil.setText("Masukkan angka yang valid!");
            }
        }
    }//GEN-LAST:event_TSuhuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKonversi;
    private javax.swing.ButtonGroup BgKonversi;
    private javax.swing.JComboBox<String> CbSkalaSuhu;
    private javax.swing.JLabel LHasil;
    private javax.swing.JLabel LJudul;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JRadioButton Rb3;
    private javax.swing.JRadioButton Rb4;
    private javax.swing.JTextField THasil;
    private javax.swing.JTextField TSuhu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
